# Generated by Django 5.2.7 on 2026-02-16 10:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('boundary', models.JSONField(default=dict, help_text='Region boundary as GeoJSON Polygon')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('check_interval', models.IntegerField(default=24, help_text='Check interval in hours')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('alert_threshold', models.FloatField(default=0.7, help_text='Confidence threshold for alerts', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OilSpillDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confidence_score', models.FloatField(help_text='ML model confidence score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('location', models.JSONField(default=dict, help_text='Detection location as GeoJSON Point')),
                ('area_size', models.FloatField(help_text='Estimated spill area in km²')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('false_positive', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cropped_image_path', models.FileField(blank=True, null=True, upload_to='detections/cropped/')),
                ('heatmap_path', models.FileField(blank=True, null=True, upload_to='detections/heatmaps/')),
                ('geojson_data', models.JSONField(blank=True, default=dict)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detection_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(default=list, help_text='List of email recipients')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='detection.oilspilldetection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source', models.CharField(choices=[('SENTINEL', 'Sentinel-1/2'), ('LANDSAT', 'Landsat 8/9'), ('CUSTOM', 'Custom Upload')], max_length=20)),
                ('acquisition_date', models.DateTimeField(db_index=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('cloud_coverage', models.FloatField(help_text='Cloud coverage percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resolution', models.FloatField(help_text='Spatial resolution in meters')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_date', models.DateTimeField(blank=True, null=True)),
                ('image_path', models.FileField(blank=True, null=True, upload_to='satellite_images/')),
                ('thumbnail_path', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('center_point', models.JSONField(default=dict, help_text='Center point as GeoJSON Point')),
                ('bounds', models.JSONField(default=dict, help_text='Image bounds as GeoJSON Polygon')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-acquisition_date'],
                'indexes': [models.Index(fields=['-acquisition_date'], name='detection_s_acquisi_e40da4_idx'), models.Index(fields=['source', 'processed'], name='detection_s_source_379608_idx')],
            },
        ),
        migrations.AddField(
            model_name='oilspilldetection',
            name='satellite_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.satelliteimage'),
        ),
        migrations.AddIndex(
            model_name='oilspilldetection',
            index=models.Index(fields=['-detection_date'], name='detection_o_detecti_a09964_idx'),
        ),
        migrations.AddIndex(
            model_name='oilspilldetection',
            index=models.Index(fields=['verified', 'false_positive'], name='detection_o_verifie_09a028_idx'),
        ),
        migrations.AddIndex(
            model_name='oilspilldetection',
            index=models.Index(fields=['confidence_score'], name='detection_o_confide_218242_idx'),
        ),
    ]
