# Generated by Django 5.2.7 on 2026-02-16 17:17

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringregion',
            name='boundary',
            field=models.JSONField(default=detection.models.default_polygon, help_text='Region boundary as GeoJSON Polygon'),
        ),
        migrations.AlterField(
            model_name='oilspilldetection',
            name='location',
            field=models.JSONField(default=detection.models.default_point, help_text='Detection location as GeoJSON Point'),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='bounds',
            field=models.JSONField(default=detection.models.default_polygon, help_text='Image bounds as GeoJSON Polygon'),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='center_point',
            field=models.JSONField(default=detection.models.default_point, help_text='Center point as GeoJSON Point'),
        ),
    ]
