# Generated by Django 5.2.7 on 2026-02-16 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('boundary', models.JSONField(default={'coordinates': [[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]], 'type': 'Polygon'}, help_text='Region boundary as GeoJSON Polygon')),
                ('active', models.BooleanField(default=True)),
                ('check_interval', models.IntegerField(default=24, help_text='Check interval in hours')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('alert_threshold', models.FloatField(default=0.7, help_text='Confidence threshold for alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OilSpillDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(help_text='ML model confidence (0-1)')),
                ('location', models.JSONField(default={'coordinates': [0, 0], 'type': 'Point'}, help_text='Center point of detection as GeoJSON Point')),
                ('affected_area', models.JSONField(default={'coordinates': [[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]], 'type': 'Polygon'}, help_text='Polygon of detected oil spill as GeoJSON')),
                ('area_size', models.FloatField(help_text='Estimated area in square kilometers')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('cropped_image_path', models.CharField(max_length=500)),
                ('heatmap_path', models.CharField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('false_positive', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detection_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(default=list)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.oilspilldetection')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('S1', 'Sentinel-1 (SAR)'), ('S2', 'Sentinel-2 (Optical)'), ('LS', 'Landsat')], max_length=2)),
                ('acquisition_date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('bounds', models.JSONField(default={'coordinates': [[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]], 'type': 'Polygon'}, help_text='Geographic bounds of image as GeoJSON Polygon')),
                ('center_point', models.JSONField(default={'coordinates': [0, 0], 'type': 'Point'}, help_text='Center point as GeoJSON Point')),
                ('image_path', models.CharField(max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('cloud_coverage', models.FloatField(blank=True, null=True)),
                ('resolution', models.FloatField(help_text='Spatial resolution in meters')),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-acquisition_date'],
                'indexes': [models.Index(fields=['-acquisition_date'], name='dashboard_s_acquisi_7ecadd_idx'), models.Index(fields=['source'], name='dashboard_s_source_8aa7d4_idx')],
            },
        ),
        migrations.AddField(
            model_name='oilspilldetection',
            name='satellite_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='dashboard.satelliteimage'),
        ),
        migrations.AddIndex(
            model_name='oilspilldetection',
            index=models.Index(fields=['-detection_date'], name='dashboard_o_detecti_7aead4_idx'),
        ),
        migrations.AddIndex(
            model_name='oilspilldetection',
            index=models.Index(fields=['severity'], name='dashboard_o_severit_804a98_idx'),
        ),
        migrations.AddIndex(
            model_name='oilspilldetection',
            index=models.Index(fields=['verified'], name='dashboard_o_verifie_90173f_idx'),
        ),
    ]
