# Generated by Django 5.2.7 on 2026-02-16 17:17

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringregion',
            name='boundary',
            field=models.JSONField(default=dashboard.models.default_polygon, help_text='Region boundary as GeoJSON Polygon'),
        ),
        migrations.AlterField(
            model_name='oilspilldetection',
            name='affected_area',
            field=models.JSONField(default=dashboard.models.default_polygon, help_text='Polygon of detected oil spill as GeoJSON'),
        ),
        migrations.AlterField(
            model_name='oilspilldetection',
            name='location',
            field=models.JSONField(default=dashboard.models.default_point, help_text='Center point of detection as GeoJSON Point'),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='bounds',
            field=models.JSONField(default=dashboard.models.default_polygon, help_text='Geographic bounds of image as GeoJSON Polygon'),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='center_point',
            field=models.JSONField(default=dashboard.models.default_point, help_text='Center point as GeoJSON Point'),
        ),
    ]
